twig:
  file_name_pattern: '*.twig'
  globals:
    app_locale: '%app_locale%'
    app_locale_str: '%app_locale_str%'
    app_settingsService: '@App\Service\SettingsService'
    app_eventService: '@App\Service\EventService'
    app_socialService: '@App\Service\SocialService'
    app_calendarService: '@App\Service\CalendarService'

when@test:
  twig:
    strict_variables: true
